server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classifier_service
    username: classifier_service_app
    password: 12345

url:
  users: http://localhost:8084/users
  audit: http://localhost:8081/audit