spring:
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user-service:8080/users
auditUrlService: http://audit-service:8080/audit