server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/classifier_service
    username: classifier_service_app
    password: 12345

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user_service:8080/api/v1/users
auditUrlService: http://audit_service:8080/api/v1/audit