name: finance

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.4
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - finance-network
  pgadmin:
    build: pgadmin
    image: pgadmin_finance:1.0.1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - finance-network
  account-service:
    build: account_service
    image: account_service_finance:1.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network
  audit-service:
    build: audit_service
    image: audit_service_finance:1.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network
  classifier-service:
    build: classifier_service
    image: classifier_service_finance:1.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network
  user-service:
    build: user_service
    image: user_service_finance:1.0.1
    environment:
      MAIL_LOGIN: ${MAIL_LOGIN}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_FIO: ${ADMIN_FIO}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
      SERVER: ${SERVER}
    networks:
      - finance-network
  proxy:
    build: proxy
    image: proxy_finance:1.0.1
    ports:
      - 80:80
    networks:
      - finance-network

networks:
  finance-network:
