name: finance

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.1
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - finance-network
  pgadmin:
    build: pgadmin
    image: pgadmin-finance:1.0.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - finance-network
  account_service:
    build: account_service
    image: account_service_finance:1.0.5
    ports:
      - 83:8080
    networks:
      - finance-network
  audit_service:
    build: audit_service
    image: audit_service_finance:1.0.4
    ports:
      - 84:8080
    networks:
      - finance-network
  classifier_service:
    build: classifier_service
    image: classifier_service_finance:1.0.4
    ports:
      - 85:8080
    networks:
      - finance-network
  user_service:
    build: user_service
    image: user_service_finance:1.0.4
    ports:
      - 86:8080
    networks:
      - finance-network
  proxy:
    build: proxy
    image: proxy_finance:1.0.0

networks:
  finance-network:
