server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: user_service_app
    password: 12345

url:
  audit: http://audit-service:8081/api/v1/audit