server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: account_service_app
    password: 12345

url:
  users: http://localhost:8084/users
  category: http://localhost:8083/category
  currency: http://localhoste:8083/currency
  audit: http://localhost:8081/audit