server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/account_service
    username: account_service_app
    password: 12345
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user_service:8080/api/v1/users
urlCabinetService: http://user_service:8080/api/v1/cabinet
urlCategoryService: http://classifier_service:8080/api/v1/classifier/operation/category
urlCurrencyService: http://classifier_service:8080/api/v1/classifier/currency