spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user-service:8080/users
urlCabinetService: http://user-service:8080/cabinet
urlCategoryService: http://classifier-service:8080/category
urlCurrencyService: http://classifier-service:8080/currency
auditUrlService: http://audit-service:8080/audit