spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user_service:8080/api/v1/users
urlCabinetService: http://user_service:8080/api/v1/cabinet
urlCategoryService: http://classifier_service:8080/api/v1/classifier/operation/category
urlCurrencyService: http://classifier_service:8080/api/v1/classifier/currency
auditUrlService: http://audit_service:8080/api/v1/audit