server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://83.166.234.152:5432/account_service
    username: account_service_app
    password: 12345

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy

urlUserService: http://user-service:8080/api/v1/users
urlCabinetService: http://user-service:8080/api/v1/cabinet
urlCategoryService: http://classifier-service:8080/api/v1/classifier/operation/category
urlCurrencyService: http://classifier-service:8080/api/v1/classifier/currency