server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service
    username: account_service_app
    password: 12345

url:
  users: http://user-service:8084/api/v1/users
  category: http://classifier-service:8083/api/v1/classifier/operation/category
  currency: http://classifier-service:8083/api/v1/classifier/currency
  audit: http://audit-service:8081/api/v1/audit